### PR TITLE
Gh 3 hotfix submodules

### PR DESCRIPTION
**Pull request by withjam**

### CODE REVIEW

**Comment by grtjn** [comment]
I'm afraid you need to undo the last commit, the one in which you put back the dev branch in the submodules config. Commits to a PR branch get auto-appended to the PR as long as it has not been merged yet.

PS: you could have edited the other PR to merge it into master.. ;-)

**Comment by grtjn** [comment]
Oh never mind, looks like it was undone by a latter commit. Did you rebase the branch against master?

**Comment by withjam** [comment]
I had started the branch from master, so it should be good to do now.

**Review by mariannemyers — APPROVED** [review]

**Comment by mariannemyers** [comment]
@withjam Looks good to me.  Go ahead and merge.

**Pull request merged**
